---

nodejs_version: "18.x"

# Prefix with distributed_press_

distributed_press_user: "press"
distributed_press_home: "/home/{{distributed_press_user}}"

# 3932 is DWEB on a phone number pad
distributed_press_port: "3932"
distributed_press_host: "localhost"
distributed_press_ipfs_provider: "builtin"
distributed_press_git_repo: "https://github.com/hyphacoop/api.distributed.press.git"
distributed_press_git_branch: "v1-staging"
distributed_press_source: "{{distributed_press_home}}/api.distributed.press"
distributed_press_service_name: "distributed.press"
