
# Vars are prefixed with distributed_press_

- name: Ensure user exists for DP service
  user:
    name: "{{distributed_press_user}}"
    append: true
    # TODO: is this needed?
    groups: adm
    shell: /bin/bash
    comment: User for the distributed.press API server

- name: "Set up node+npm"
  include_role:
    name: geerlingguy.nodejs

- name: Add distributed.press systemd service
  template:
    src: distributed.press.service.j2
    dest: "/etc/systemd/system/{{distributed_press_service_name}}.service"

- name: "Stop distributed.press service to recompile"
  systemd:
    state: stopped
    name: "{{distributed_press_service_name}}"

- name: Clone or update DP codebase
  become: yes
  become_user: "{{distributed_press_user}}"
  git:
    repo: "{{distributed_press_git_repo}}"
    version: "{{distributed_press_git_branch}}"
    dest: "{{distributed_press_source}}"
    clone: yes
    update: yes

- name: Install NPM Dependencies
  become: yes
  become_user: "{{distributed_press_user}}"
  shell: |
    cd {{distributed_press_source}}
    npm ci

#- name: Nuke cache and protocol config
#  become: yes
#  become_user: "{{distributed_press_user}}"
#  shell: |
#    cd {{distributed_press_source}}
#    npm run nuke

- name: "Enable Node to bind to port 53 for DNS"
  shell: setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/node

- name: "Enable DNS traffic through firewall"
  shell: "iptables -A INPUT -p udp -m udp --dport 53 -j ACCEPT"

- name: "Enable libp2p udp traffic through firewall"
  shell: "iptables -A INPUT -p udp -m udp --dport 7976 -j ACCEPT"

- name: "Enable libp2p tcp traffic through firewall"
  shell: "iptables -A INPUT -p tcp -m tcp --dport 7976 -j ACCEPT"

#- name: Build service
#  become: yes
#  become_user: "{{distributed_press_user}}"
#  shell: |
#    cd {{distributed_press_source}}/v1
#    npm run build

- name: "Run distributed.press service"
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "{{distributed_press_service_name}}"
