---

all:
  # Set custom variables here, like custom ports for listening
  vars:
    distributed_press_domain: "example.com"
    distributed_press_letsencrypt_email: "example@example.com"
    distributed_press_served_sites: []
  children:
    distributed_press:
      hosts:
        example.com:
          ansible_user: root
