name: Lint
on:
  push:
    branches-ignore: [main, v1]
  pull_request:
    branches: [main, v1]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: v1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TYPESCRIPT_STANDARD: true
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .*v0/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
